name: EFP Bot Run Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'  # This runs every 2 hours
  workflow_dispatch:  # This allows manual triggering

jobs:
  run_efp_bot:
    runs-on: ubuntu-latest
    timeout-minutes: 110  # Set a 110-minute timeout (just under 2 hours)
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run EFP Bot
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: python efp_bot.py
    
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "2-hourly update from GitHub Actions" && git push)