name: EFP Bot Run Every 8 Hours

on:
  schedule:
    - cron: '0 */8 * * *'  # This runs every 8 hours (at 00:00, 08:00, and 16:00 UTC)
  workflow_dispatch:  # This allows manual triggering

jobs:
  run_efp_bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install backoff  # Add this line to install backoff module
    
    - name: Run EFP Bot
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        python efp_bot.py &
        sleep 7h  # Allow the script to run for 7 hours
        kill $!  # Terminate the script after 7 hours
    
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "8-hourly update from GitHub Actions" && git push)